name: docker_push
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: thesixonenine/get_weibo_hot:latest
#      - name: Build image
#        run: |
#          docker build . --file Dockerfile
#          docker tag get_weibo_hot thesixonenine/get_weibo_hot
#          docker push thesixonenine/get_weibo_hot
